version: '1.0'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24

services:

  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: